name: Framework Validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:

  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release
  REST_PATH: /rest/detectorlib/install
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  framework-validation:
    uses: rest-for-physics/framework/.github/workflows/validation.yml@jgalan-readoutplane-update
